import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { DailyDistill } from "../../schemas/distill.js";
import { logger } from "../../utils/logger.js";
import { getProjectDataDir } from "../../utils/paths.js";

const DECISIONS_DIR = "decisions";
const INDEX_FILE = "index.json";

interface DecisionRecordEntry {
  id: string;
  date: string;
  title: string;
  domain: string | undefined;
  hds: number;
  classification: string;
}

/**
 * Generate lightweight decision records for decisions with
 * HDS > 0.6 AND alternativesConsidered >= 2.
 * Writes markdown ADRs to .unfade/decisions/DR-{date}-{seq}.md
 * and maintains an index at .unfade/decisions/index.json.
 */
export function generateDecisionRecords(distill: DailyDistill, cwd?: string): number {
  const qualifying = distill.decisions.filter((d) => (d.alternativesConsidered ?? 0) >= 2);

  if (qualifying.length === 0) return 0;

  const decisionsDir = join(getProjectDataDir(cwd), DECISIONS_DIR);
  mkdirSync(decisionsDir, { recursive: true });

  const index = loadIndex(decisionsDir);
  let generated = 0;

  for (let i = 0; i < qualifying.length; i++) {
    const dec = qualifying[i];
    const seq = String(i + 1).padStart(2, "0");
    const id = `DR-${distill.date}-${seq}`;
    const filename = `${id}.md`;
    const filePath = join(decisionsDir, filename);

    if (existsSync(filePath)) continue;

    const hds = distill.directionSummary?.averageHDS ?? 0;
    const classification =
      hds >= 0.6 ? "Human-Directed" : hds >= 0.3 ? "Collaborative" : "LLM-Directed";

    const markdown = formatDecisionRecord(id, dec, distill.date, hds, classification);
    writeFileSync(filePath, markdown, "utf-8");

    index.push({
      id,
      date: distill.date,
      title: dec.decision,
      domain: dec.domain,
      hds,
      classification,
    });

    generated++;
  }

  if (generated > 0) {
    writeFileSync(join(decisionsDir, INDEX_FILE), `${JSON.stringify(index, null, 2)}\n`, "utf-8");
    logger.debug("Generated decision records", { count: generated, date: distill.date });
  }

  return generated;
}

function formatDecisionRecord(
  id: string,
  decision: DailyDistill["decisions"][0],
  date: string,
  hds: number,
  classification: string,
): string {
  const lines = [
    `# ${id}: ${decision.decision}`,
    "",
    `- **Status:** Accepted`,
    `- **Date:** ${date}`,
    `- **HDS:** ${hds.toFixed(2)} (${classification})`,
    `- **Domain:** ${decision.domain ?? "general"}`,
    `- **Decision:** ${decision.decision}`,
    `- **Alternatives Considered:** ${decision.alternativesConsidered ?? 0}`,
    `- **Rationale:** ${decision.rationale}`,
    "",
    "---",
    "",
    `_Auto-generated by Unfade on ${new Date().toISOString()}_`,
    "",
  ];
  return lines.join("\n");
}

function loadIndex(decisionsDir: string): DecisionRecordEntry[] {
  const indexPath = join(decisionsDir, INDEX_FILE);
  if (!existsSync(indexPath)) return [];
  try {
    return JSON.parse(readFileSync(indexPath, "utf-8"));
  } catch {
    return [];
  }
}
